apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
  labels:
    app: postgress-deployment
    type: demo-voting-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgress-pod
      type: demo-voting-app
  template:
    metadata: 
      name: postgress-pod
      labels:
        app: postgress-pod
        type: demo-voting-app
    spec:
      containers:
      - name: postgress
        image: postgres
        ports:
        - containerPort: 5432
        env: 
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
    