apiVersion: apps/v1
kind: Deployment
metadata: 
  name: result-deployment 
  labels: 
    app: result-deployment
    type: demo-voting-app
spec:
  replicas: 1
  template: 
    metadata:
      name: result-pod
      labels:
        app: result-pod
        type: demo-voting-app
    spec:
      containers:
      - name: result-app
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80
  selector:
    matchLabels:
      app: result-pod
      type: demo-voting-app
