apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker-deployment
    type: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-pod
      type: demo-voting-app
  template:
    metadata:
      name: worker-pod
      labels:
        app: worker-pod
        type: demo-voting-app
    spec:
      containers:
      - name: worker-app
        image: kodekloud/examplevotingapp_worker:v1
