apiVersion: v1
kind: Service
metadata:
  name: db #code identifies postgress as DB so we need to name it db
  labels:
    app: postgress-clusterip-service
    type: demo-voting-app
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgress-pod
    type: demo-voting-app
