apiVersion: v1
kind: Service 
metadata: 
  name: redis #code identifies redis DB as "redis" so we need to name it redis
  labels:
    app: redis-clusterip-service
    type: demo-voting-app
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-pod
    type: demo-voting-app