apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: result-service
    type: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: result-pod
    type: demo-voting-app
